[theme]
base = "light"
primaryColor = "#1e3a8a"
backgroundColor = "#f3f4f6"
# Kita kembalikan ini jadi putih agar kotak isian (input) terang benderang
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "sans serif"